services:
  db-events:
    image: postgres:16
    environment:
      - POSTGRES_DB=eventsdb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - events-db-data:/var/lib/postgresql/data

  backend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db-events:5432/eventsdb
      - JWT_SECRET=super_secret
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db-events

  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend

volumes:
  events-db-data:
